# Generated by Django 2.2 on 2021-06-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0002_auto_20210605_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reg_login.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wallMessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_content.WallMessage'),
        ),
        migrations.AlterField(
            model_name='wallmessage',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallMessages', to='reg_login.User'),
        ),
    ]
